encyclopedia/urls.py
from django.urls import path

from . import views

app_name = 'encyclopedia'
urlpatterns = [
    path('', views.index, name='index'),
    path('search', views.search, name='search'),
    path('create_page', views.create_page, name='create_page'),
    path('random_page', views.random_page, name='random_page'),
    path('<str:entry>', views.content, name='entry'),
    path('<str:entry>/edit', views.edit_page, name='edit_page')
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from audioop import reverse
from email import message
import django
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.safestring import mark_safe

from . import util

import random
import markdown2

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


def content(request, entry):
    content = util.get_entry(entry)

    if not content:
        return render(request, "encyclopedia/apology.html", {
            "message": "Not_Found",
        })

    return render(request, "encyclopedia/content.html", {
        "content": mark_safe(markdown2.markdown(content)),
        "title": entry,
    })


def search(request):
    entry = request.POST['entry']
    return redirect(reverse('encyclopedia:entry', kwargs={'entry': entry}))

    
def create_page(request):
    titles = util.list_entries()

    if request.method == 'POST':
        title = request.POST['title']
        content = request.POST['content']

        if not title:
            return render(request, "encyclopedia/new_page.html", {
                "error_message": "The title can't be empty",
            }) 

        if title not in titles:
            with open(f"entries/{title}.md", 'w+') as f:
                f.write(content)
            return render(request, "encyclopedia/new_page.html", {
                "success_message": "Successful!",
            }) 
        else:
            return render(request, "encyclopedia/new_page.html", {
                "error_message": "The file already exist",
            }) 

    return render(request, "encyclopedia/new_page.html")


def edit_page(request, entry):
    content = util.get_entry(entry)

    if request.method == 'POST':
        title = request.POST['title']

        with open(f"entries/{title}.md", 'a') as f:
            f.write(content)
        return redirect(reverse('encyclopedia:entry', kwargs={'entry': title}))

    return render(request, "encyclopedia/edit_page.html", {
        "title": entry,
        "content": content,
    })


def random_page(request):
    titles = util.list_entries()
    random_title = random.choice(titles)
    return redirect(reverse('encyclopedia:entry', kwargs={'entry': random_title}))

encyclopedia/templates/encyclopedia/apology.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    
{% endblock %}

{% block body %}
    
    <div class="container text-center flex-container">
        <div>
            <h1>Sorry</h1>
            <img src="https://api.memegen.link/images/custom/404/{{ message }}.gif?height=375&width=400&background=https%3A%2F%2Fmedia1.giphy.com%2Fmedia%2F1ClXktIXoounm%2Fgiphy.gif&token=0hgefu12ey830pj22koi" alt="404">
        </div>
    </div>

{% endblock %}

encyclopedia/templates/encyclopedia/content.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ content }}
{% endblock %}

{% block body %}

    <div class="container">
        <div class="mb-3">
            {{ content }}
        </div>
        <div class="mb-2">
            <a role="button" class="btn btn-outline-primary" href="{% url 'encyclopedia:edit_page' title %}">Edit</a>
        </div>
    </div>
{% endblock %}

encyclopedia/templates/encyclopedia/edit_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h2>New Page</h2>

    <div class="container">
        <form action="{% url 'encyclopedia:edit_page' title %}" method="post">
            {% csrf_token %}
            {% if success_message %}
                <div class="alert alert-success" role="alert">
                    {{ success_message }}
                </div>
            {% endif %}
            <div class="mb-3">
                <input type="hidden" value="{{ title }}" name="title">
                <label for="content" class="form-label">Content</label>
                <textarea class="form-control" id="content" style="height: 300px" name="content">{{ content }}</textarea>
            </div>
            <div class="mb-3">
                <input class="btn btn-outline-primary" type="submit" value="Save">
            </div>
        </form>
    </div>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h2>All Pages</h2>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="container-fluid">
            <div class="row main">
                <div class="col-xxl-2 col-md-6 bg-light px-4 py-4">
                    <h2>Wiki</h2>
                    <div class="mb-3">
                        <form action="{% url 'encyclopedia:search' %}" method="post">
                            {% csrf_token %}
                            <input class="form-control mb-3" type="text" name="entry" placeholder="Search Encyclopedia">
                            <input class="btn btn-primary" type="submit" value="Search">
                        </form>
                    </div>
                    <div class="memu ps-2">
                        <div>
                            <a href="/wiki">Home</a>
                        </div>
                        <div>
                            <a href="{% url 'encyclopedia:create_page' %}">Create New Page</a>
                        </div>
                        <div>
                            <a href="{% url 'encyclopedia:random_page' %}">Random Page</a>
                        </div>
                    </div>
                    {% block nav %}
                    {% endblock %}
                </div>
                <div class="col-xxl-10 col-md-6 px-4 py-4">
                    {% block body %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

encyclopedia/templates/encyclopedia/new_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h2>New Page</h2>

    <div class="container">
        <form action="{% url 'encyclopedia:create_page' %}" method="post">
            {% csrf_token %}
            {% if success_message %}
                <div class="alert alert-success" role="alert">
                    {{ success_message }}
                </div>
            {% endif %}
            {% if error_message %}
                <div class="alert alert-danger" role="alert">
                    {{ error_message }}
                </div>
            {% endif %}
            <div class="mb-3">
                <label for="title" class="form-label">Title</label>
                <input type="text" class="form-control" id="title" name="title">
              </div>
              <div class="mb-3">
                <label for="content" class="form-label">Content</label>
                <textarea class="form-control" id="content" style="height: 300px" name="content"></textarea>
              </div>
              <div class="mb-3">
                <input class="btn btn-outline-primary" type="submit" value="Save">
              </div>
        </form>
    </div>

{% endblock %}